# Generated by Django 4.0.5 on 2022-07-03 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createclass',
            old_name='class_name',
            new_name='class_code_name',
        ),
        migrations.RenameField(
            model_name='createclass',
            old_name='subject',
            new_name='subject_name',
        ),
    ]
