# Generated by Django 4.0.5 on 2022-07-05 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddClassWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mytopic', models.CharField(choices=[('Assignment', 'Assignment'), ('Presentation', 'Presentation'), ('Exam Info', 'Exam Info')], default='Presentation', max_length=20)),
                ('title', models.TextField(default='none', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('imagephoto', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('current_date', models.DateTimeField(auto_now_add=True)),
                ('end_date_time', models.DateTimeField(blank=True, null=True)),
                ('myclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.createclass')),
            ],
        ),
    ]
