# Generated by Django 4.0.5 on 2022-07-11 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0009_alter_quesmodel_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quesmodel',
            name='topics',
            field=models.CharField(default='new', max_length=200),
        ),
    ]
