# Generated by Django 4.0.5 on 2022-08-13 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0011_viewcourse_addcourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addcourse',
            name='link_course',
        ),
        migrations.AddField(
            model_name='addcourse',
            name='link1',
            field=models.URLField(default='n', null=True),
        ),
        migrations.AddField(
            model_name='addcourse',
            name='link10',
            field=models.URLField(default='n', null=True),
        ),
        migrations.AddField(
            model_name='addcourse',
            name='link2',
            field=models.URLField(default='n', null=True),
        ),
        migrations.AddField(
            model_name='addcourse',
            name='link3',
            field=models.URLField(default='n', null=True),
        ),
        migrations.AddField(
            model_name='addcourse',
            name='link4',
            field=models.URLField(default='n', null=True),
        ),
        migrations.AddField(
            model_name='addcourse',
            name='link5',
            field=models.URLField(default='n', null=True),
        ),
        migrations.AddField(
            model_name='addcourse',
            name='link6',
            field=models.URLField(default='n', null=True),
        ),
        migrations.AddField(
            model_name='addcourse',
            name='link7',
            field=models.URLField(default='n', null=True),
        ),
        migrations.AddField(
            model_name='addcourse',
            name='link8',
            field=models.URLField(default='n', null=True),
        ),
        migrations.AddField(
            model_name='addcourse',
            name='link9',
            field=models.URLField(default='n', null=True),
        ),
    ]
