# Generated by Django 4.0.5 on 2022-08-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0013_alter_addcourse_link1_alter_addcourse_link10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcourse',
            name='link1',
            field=models.CharField(default='none', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='addcourse',
            name='link10',
            field=models.CharField(default='none', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='addcourse',
            name='link2',
            field=models.CharField(default='none', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='addcourse',
            name='link3',
            field=models.CharField(default='none', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='addcourse',
            name='link4',
            field=models.CharField(default='none', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='addcourse',
            name='link5',
            field=models.CharField(default='none', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='addcourse',
            name='link6',
            field=models.CharField(default='none', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='addcourse',
            name='link7',
            field=models.CharField(default='none', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='addcourse',
            name='link8',
            field=models.CharField(default='none', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='addcourse',
            name='link9',
            field=models.CharField(default='none', max_length=200, null=True),
        ),
    ]
