# Generated by Django 4.0.5 on 2022-08-18 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0014_alter_addcourse_link1_alter_addcourse_link10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createclass',
            name='section',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='createclass',
            name='subject_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='viewcourse',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='viewcourse',
            name='img_course',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
