# Generated by Django 4.0.3 on 2022-08-21 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teacher', '0016_alter_addclasswork_marks'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinClassteach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.createclass')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
