# Generated by Django 4.0.5 on 2022-08-10 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
        ('teacher', '0010_alter_quesmodel_topics'),
        ('student', '0002_commentmain'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudnetWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.FileField(upload_to='images/')),
                ('mystu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.student')),
                ('mywork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.addclasswork')),
            ],
        ),
    ]
