# Generated by Django 4.0.3 on 2022-08-20 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_studnetwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annoucemain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.commentmain')),
            ],
        ),
    ]
