# Generated by Django 4.0.3 on 2022-08-20 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_replycomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='replycomment',
            name='text',
            field=models.CharField(default='new', max_length=400),
        ),
    ]
