# Generated by Django 4.0.3 on 2022-08-25 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0001_initial'),
        ('student', '0006_commentmain_myteach_alter_commentmain_mystu'),
    ]

    operations = [
        migrations.AddField(
            model_name='studnetwork',
            name='teachwork',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studnetwork',
            name='mystu',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.student'),
        ),
    ]
